### ISSUE TITLE
Issue Cadastrar Animal para Adoção

### ISSUE THREAD

**Issue by PedroLomonaco** [Wyru/mascotes-a-salvo#11]
- Implementar os campo de "Fotos", "Quantidade", "Espécie" e "Descrição" de acordo com o DRE
- Implementar a validação da Data de Nascimento (mandar uma mensagem de erro quando for digitada incorretamente)
- Trocar o nome do campo "Relatório" para "Laudo"

**Comment by Wyru** [comment]
Uma modificação foi realizada para facilitar o uso dos pets em outras funcionalidades. Agora eles são separados da doação, assim o usuário deve cadastrar os pets antes de doá-los.
